### ISSUE TITLE
[React 16.3] - Context provider and consumer's displayName not being used

### ISSUE THREAD

**Issue by ferdaber** [facebook/react-devtools#1008]
I realize this is a bit early, but in React 16.3 with the new context API, the provider and the consumer's respective `displayName`s are not being used in react devtools.

codesandbox with minimal reproduction:
https://codesandbox.io/s/302ymvn1j1

![image](https://user-images.githubusercontent.com/12239873/38121726-c6eda7f4-3396-11e8-83af-b4b7e3edc999.png)

**Comment by gaearon** [comment]
Happy to take a fix!

**Comment by ackvf** [comment]
Yes please!
![image](https://user-images.githubusercontent.com/2313018/39564556-fd4ee82e-4eb4-11e8-8e44-011d42ed30c1.png)

**Comment by gaearon** [comment]
@ackvf If you want to fix this, you're welcome! Otherwise "+1" comments don't really help anyone. We know what the issue is about :-)

**Comment by ferdaber** [comment]
I'll try my hand and making a PR to fix this, thanks!

**Comment by gokul0** [comment]
Hi @gaearon 

I am a rookie to Github. I would like to contribute to this issue. I have been working on this from morning 9 AM IST. But, I could not get anything yet. Is there a specific direction I should look into? Can u or anyone guide me on this just a little bit?

**Comment by benwiley4000** [comment]
Hey @gaearon, just a ping to remind you that @nanovazquez opened a PR to fix this! :slightly_smiling_face:

**Comment by nanovazquez** [comment]
Hey @bvaughn @gaearon, a friendly reminder that [this PR](https://github.com/facebook/react-devtools/pull/1031) fixes the issue and is sitting for months with no review. Since then, I've been fixing the conflicts because of the changes pushed. 

I understand if you guys are busy and I'm sorry to bother you directly, but at this point, I need to ask. Is there a way I can help to move the PR forward? Or is it a no-go? I'd really want to avoid fixing conflicts a fifth time.
