### ISSUE TITLE
Multiple monitor setup with 4K break scrollbar size in devtools

### ISSUE THREAD

**Issue by jonathanlaf** [facebook/react-devtools#1026]
**Environment** 
- Google Chrome : 66.0.3359.139 (64-bit)
- Revision : a020eddf0d85fe84d4a6787b304f50aafb670969-refs/branch-heads/3359@{#767}
- OS : Windows 10
- JavaScript : V8 6.6.346.26
- Three monitors
    - One 4K (3840x2160) with the Scale and layout options of windows set at 250%
    - Two FullHD (1920 x 1080) with the Scale and layout options of windows set at 100%

**Actual Behavior** 

If I open the Devtools in the 4k screen the scrollbars are the right size. But if I open them in one of my other screens, they look to take the 250% Scale from the 4K. I have to move my Devtools from HD screen to the 4K then back to HD to fix the scrollbars. 

**Desired Behavior** 

The scrollbars should always reflect the actual monitor resolution and scale. 

![image](https://user-images.githubusercontent.com/3685529/39720991-72932b24-5214-11e8-852d-b755b1541061.png)

**Comment by bvaughn** [comment]
Scrollbars are part of the browser chrome. (We don't do anything special to style them or customize them in any way.) I believe this bug is related to your OS+browser (or perhaps a browser plugin)

**Comment by jonathanlaf** [comment]
Oh sorry about that. Since I had no problem with the other tabs of chrome I was sure the bug was from your side.

**Comment by bvaughn** [comment]
That's understandable. Maybe the bug is limited to Chrome extensions, and so not something you'd see on websites.

Some possibly related threads (though I only briefly skimmed them):
* https://productforums.google.com/forum/#!topic/chrome/ViYbXA8TPCA
* https://bugs.chromium.org/p/chromium/issues/detail?id=349822
* https://github.com/electron/electron/issues/8513

I'm going to close this for now since I don't think it is anything React DevTools specific, but thanks for bringing it to our attention. 😄
