### ISSUE TITLE
Firefox doesn't reload React tools when navigating

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#103]

**Comment by qnm** [comment]
Perhaps relating to this, it also doesn't reload when hot-reloading takes place.

**Comment by jaredly** [comment]
Yeah - I haven't yet figured out if there's a handy API for being notified when a navigation occurs, akin to `chrome.devtools.network.onNavigated`

**Comment by canuckistani** [comment]
@jaredly I think you'll want to listen for events on the [tabs api](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#Events_2), there are events for 'open', 'load' and '[pageshow](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#pageshow)', I think the last one is the most likely one because it triggers even if the page is loaded from the cache.

Really excited to see Firefox support here!

**Comment by jaredly** [comment]
@canuckistani perfect! exactly what I needed. I put up a PR - let me know what you think
https://github.com/facebook/react-devtools/pull/117
