### ISSUE TITLE
Feature: List component updated and the number of updates.

### ISSUE THREAD

**Issue by joetidee** [facebook/react-devtools#1059]
Hello, I was wondering if the tools could include an additional feature. Currently there is a 'highlight updated' feature and thought it would be great to extend this a little to add a 'list updates' feature. For example, when enabled and when you make interactions in the browser, it will display the name of the component with the number of prop updates and state updates:

| Component Name        | No. Receive Triggers           | No. State Triggers  |
| ------------- |:-------------:|:-----:|
| SomeComponent      | 2 | 0 |
| AnotherComponent      | 3      |   2 |

etc...

Also, a button to clear the list would be useful.

**Comment by bvaughn** [comment]
I don't think we'll build this functionality exactly as described, but there is some overlap with my recent work on a profiler plug-in, as well as showing the number of times a component renders (but not the underlying cause, since I think this is kind of muddy with e.g. state batching)

I'm going to close this issue and track the render-count display via #1078 😄
