### ISSUE TITLE
Make DevTools run faster

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1080]
Based on some user recent feedback I gathered [via Twitter](https://twitter.com/brian_d_vaughn/status/1025776259056336897), one common sentiment is that DevTools are too slow.

We might be able to speed them up somewhat by reducing the amount of info displayed (#1079). We might also try replacing our current tree view with something built on top of e.g. [react-window](https://github.com/bvaughn/react-window). We might also try removing some cruft like the Relay Classic plug-in.

This is more of an investigation task as I don't know the causes of the slowness.

**Comment by digitarald** [comment]
Since Firefox DevTools is focussed on performance for a few releases now, I thought I jump in and profile a bit using Firefox's platform profiler (perfect fit for this as it profiles the whole browser with all processes).

Just some preliminary results:

I filed an [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1481310) on the Firefox side for slow canvas rendering (profiles collected there highlight the slow canvas calls). Looks like WebRender will fix the canvas issue mostly.

This a profile from a Surface Pro (Nightly with WebRender), navigating quickly through the tree: https://perfht.ml/2vHP93K

Most time is spend in JS. I need to re-profile with development mode to get the performance markers.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
