### ISSUE TITLE
Add please the setting for indentation

### ISSUE THREAD

**Issue by Popugune** [facebook/react-devtools#1108]
Add please the setting for indentation. Not very convenient is a "ladder" of components with such indentations.

**Comment by gaearon** [comment]
@Popugune Please provide screenshots, it's not clear at all what you're talking about.

**Comment by bvaughn** [comment]
Indenting to reflect the nesting / hierarchy of elements in the tree is intentional and following the precedent set by browser devtools "Elements" panel. I don't think we should/will make this configurable because it would add complexity.

If you're requesting something else, please provide more info and screenshots and we can re-open and talk 😄
