### ISSUE TITLE
Elements: Auto scroll to show selected node when collapsed/expanded

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1132]
Feedback from PR #1112

the autoscroll doesn't seem to trigger on node collapse/expansion via keyboard (left and right arrow buttons). would be nice if it did

![](https://cl.ly/0f16305ee78b/download/Screen%252520Recording%2525202018-08-27%252520at%25252004.57%252520pm.gif)

**Comment by gaearon** [comment]
You said you couldn't reproduce before so here are detailed instructions.

1. Install 3.3.2 from the Chrome store
2. Go to https://reactjs.org/tutorial/tutorial.html
3. Go to React tab, use "click to select" and locate the sidebar `<ul>`
4. Select sidebar `<ul>`
5. Scroll down a bit until `<ul>` is no longer visible (but still selected)
6. Press left and right arrows

Expected: when I press left and right arrows with `ul` selected, the `ul` should jump back into view because I'm interacting with it. Actual: scroll is not adjusted so I just see the content shifting.

![](https://dzwonsemrish7.cloudfront.net/items/2i1o002x3D2G0Z3O0l1x/Screen%20Recording%202018-08-31%20at%2002.27%20PM.gif?v=a6f59b3d)

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
