### ISSUE TITLE
error with react chrome extension

### ISSUE THREAD

**Issue by sushmasridurga** [facebook/react-devtools#1159]
Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See https://www.chromestatus.com/feature/5527160148197376 for more details
3backend.js:760 Uncaught TypeError: Cannot read property 'nativeObjectCreate' of undefined
    at Object.<anonymous> (backend.js:760)
    at __webpack_require__ (backend.js:20)
    at Object.<anonymous> (backend.js:742)
    at __webpack_require__ (backend.js:20)
    at setup (backend.js:74)
    at welcome (backend.js:70)

**Comment by joshi1983** [comment]
To get to the point, I doubt this problem is related to React.

I ran into this problem with Chrome Version 69.0.3497.100 (Official Build) (64-bit) on Windows 8.1.

This bug report on Chromium looks related although it is more concerned with the wording of the message:
https://bugs.chromium.org/p/chromium/issues/detail?id=883173

**Comment by dzienisz** [comment]
It happen when you have too much DOM nodes element to load like 3000+. It have nothing with react-devtools. Consider closing.

**Comment by bvaughn** [comment]
Closing due to lack of info.

**Comment by engmyahya** [comment]
Sorry, I knew that it was closed, but I met this issue, and my problem was that the project located in a long directory. Once I moved the project folder to a shorter directory, the message disappeared.

**Comment by Daniieloo10** [comment]
change in the server side the 302 status to another status
