### ISSUE TITLE
[React-Native][Android] Cannot inspect elements

### ISSUE THREAD

**Issue by pavermakov** [facebook/react-devtools#1184]
Recently I've upgraded react-devtools from 2.5.0 to 3.3.2. I've noticed that I was no longer able to inspect elements both on an android emulator and a real android device.

**Devices used:**
- OnePlus One (Android version - 6.0.1)
- Pixel XL emulator (Android version - 8.1.0)

<img width="311" alt="46671277-082a4900-cbdd-11e8-94a1-5e4e3d7d2ff4" src="https://user-images.githubusercontent.com/10779996/46798932-05a22d80-cd5c-11e8-8af4-b14ee6abbf8b.png">

I had to to switch back to the older version for the inspector to work again.

**Comment by bvaughn** [comment]
Can you confirm that both [`react-devtools`](https://www.npmjs.com/package/react-devtools) (the thing you run from the command line) and [`react-devtools-core`](https://www.npmjs.com/package/react-devtools-core) (the thing that's bundled along with your React Native app source) are running the same versions? If you've updated `react-devtools` to 3.3.2 but `react-devtools-core` is still 2.5.0 then it's expected that they would not work together.

Since I haven't heard any other reports of this, I'm pretty sure that's what happened. If that's not the case, please let us know and we can look into this more.
