### ISSUE TITLE
Need certified HTTPS for internet explorer inside Word

### ISSUE THREAD

**Issue by duttaoindril** [facebook/react-devtools#1208]
Yes, I'm developing in an IE 11 iFrame inside word. If I try to run the script or do an import, it gives security errors - so converting this to https://localhost:8097 would be very helpful.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
