### ISSUE TITLE
Version 3.4.2 not working on Firefox 56

### ISSUE THREAD

**Issue by chavab1** [facebook/react-devtools#1221]
The dev tool works fine on Chrome but I can't get it to work on Firefox. I see the icon on my top nav and the tab in my developer toolbar. However, the react panel is empty. I tested it on React's main website as instructed but I get the same results.

I'm using Firefox 56 since I rely heavily on FireFTP and last checked the newest version of Firefox is incompatible with FireFTP. Is there a specific version I should use to get the dev tool to work on FF56??

Thanx

**Comment by bvaughn** [comment]
Since Firefox is an evergreen browser, we don't really make an active effort to support older versions (and the last release of 56 was over a year ago).

That being said, I just installed [56.0.2](https://ftp.mozilla.org/pub/firefox/releases/56.0.2/mac/en-US/) temporarily and confirmed that React DevTools does indeed seem to fail on that version.

**Comment by bvaughn** [comment]
Unfortunately I can't even debug this because when I try, Firefox errors with:
> Error: Must pass a port in an env variable with MOZ_BROWSER_TOOLBOX_PORT
connect@chrome://devtools/content/framework/toolbox-process-window.js:67:11
@chrome://devtools/content/framework/toolbox-process-window.js:117:11

Firefox does not make it easy to run and test old versions. Doing a really quick test just now, it looks like DevTools supports Firefox 59+ only.

I vaguely remember some new extensions APIs being added to Firefox at some point that we depend on, but I thought that was in v54.

Unfortunately I don't have the bandwidth to debug this really. If you'd like to dig in more I'd love to help, otherwise (at least for now) I think we won't be able to do much.

**Comment by bvaughn** [comment]
Closing due to lack of response~
