### ISSUE TITLE
Unable to highlight elements with high z-index property value

### ISSUE THREAD

**Issue by herodrigues** [facebook/react-devtools#1268]
When inspecting React rendered elements using the standalone package, I'm unable to highlight elements with a high z-index value.

The purple element on the right is inside a shadow DOM which has z-index set to 10000000 (same as the injected div by `react-devtools`)

![image](https://user-images.githubusercontent.com/1832537/50702081-a0926700-102e-11e9-813a-376a86074a65.png)

If I set it to 10000001 (or any value higher than this), I'm only able to see the margin element highlighted.

![image](https://user-images.githubusercontent.com/1832537/50702216-ff57e080-102e-11e9-9270-7d270b72812d.png)

Wasn't that supposed to have a higher z-index property value to stay in front of any possible element?

**Comment by bvaughn** [comment]
The highlighter overlay has a [hard-coded `z-index` value of 10,000,000](https://github.com/facebook/react-devtools/blob/bcf6b1aaf3e15b67b5c797f95c639c810c13db32/frontend/Highlighter/Overlay.js#L78-L80). I think this is a reasonable approach.

The alternative would be to update the [`inspect` method](https://github.com/facebook/react-devtools/blob/bcf6b1aaf3e15b67b5c797f95c639c810c13db32/frontend/Highlighter/Overlay.js#L95) to  to to try to ensure that it's always higher than the element being inspected, but I think this would actually be complicated– since it would require us to account for [the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). (An element could have a higher `z-index` because of one of its ancestors.)

I think our current solution is good enough for the common case. 😄 PRs are always welcome though if you have ideas or suggestions! This isn't something I've thought about much.

**Comment by herodrigues** [comment]
Thanks for the explanation.

I think setting an even higher `z-index` value would be a good solution, but I'm not sure if this deserves a PR.

I've solved this issue by setting `z-index` to 10^6 in development and setting a higher value in production.
Fair enough considering I'm bringing a really corner case.
