### ISSUE TITLE
[Chrome extension] Vivaldi crashes when opening dev tools

### ISSUE THREAD

**Issue by Pumpuli** [facebook/react-devtools#1346]
Since the release of Vivaldi 2.5 (2.5.1525.40 to be exact) a couple of days ago, the whole browser crashes when I try to open dev tools. This happens on all websites. After disabling the React DevTools extension, I can open dev tools without crashing.

I've ran into this on Windows 8 and Windows 10.

**Comment by bvaughn** [comment]
This is the first I've even heard of Vivaldi 😅(Sounds like maybe they broke something to do with the extension API with their recent release?)

Anyway, Vivaldi is not one of our supported browsers (Chrome/Firefox) so you're kind of own your own if you want to use this extension in it.

If you are able to identify the problem and submit a PR, we could take a look though. Otherwise...sorry! 😦

**Comment by lalomartins** [comment]
For the record, in case anyone else gets here from google:

For me, it crashes if the devtools are undocked, but works fine when docked.

**Comment by Pumpuli** [comment]
Ok, I was using undocked devtools...

Also, looks like with the new v4 it doesn't crash anymore! :tada:

**Comment by bvaughn** [comment]
> Also, looks like with the new v4 it doesn't crash anymore! 🎉

Yay!
