### ISSUE TITLE
New Devtools: Where is Highlight Updates?

### ISSUE THREAD

**Issue by k3flo** [facebook/react-devtools#1377]
I just noticed that react devtool were updated. I'm missing the "Highlight Updates" function.
How can I activate it?

![image](https://user-images.githubusercontent.com/12381373/63153924-c8f43200-c00f-11e9-8d00-64a9035d6dc2.png)

![image](https://user-images.githubusercontent.com/12381373/63153936-cdb8e600-c00f-11e9-8dec-2cead3055699.png)

**Comment by lschin** [comment]
Facing the same issue

**Description**
Adds React debugging tools to the Chrome Developer Tools. Created from revision 2bcc6c6 on 8/15/2019.

**Version**
4.0.2 (8/15/2019)

**Comment by wryanzimmerman** [comment]
Same issue here; hopefully the button was just moved?

**Comment by hoodwink73** [comment]
Found this on [twitter](https://twitter.com/brian_d_vaughn/status/1162393047352500227), the omission of **Highlight Updates** was deliberate.

Reading the [thread](https://www.reddit.com/r/reactjs/comments/cqx554/introducing_the_new_react_devtools/ex1r9nb/), it seems they are re-evaluating how to signal performance problems caused by re-renders. Till then, they are encouraging you to use the profiler.

**Comment by llmdev** [comment]
Please come back with hightlight updates, I understand that the profiler can help us a lot, but the visual presentation is much easier and faster for a debugger

**Comment by bvaughn** [comment]
This issue has already been reported in the main React repo:
https://github.com/facebook/react/issues/16437

This repository is for the legacy DevTools extension (v3) and is in the process of being shut down.

Thank you!
