### ISSUE TITLE
Changes made in elements tab not reflected in react tab

### ISSUE THREAD

**Issue by deepak1556** [facebook/react-devtools#2]
ex: Deleting a node or changing attributes of a node not seem to be reflected in reacts tab.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
Looks like this issue is a "won't fix"
In the [new version of devtools](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html) you can search for components, and there's a visual link to the rendered page. If there are other features you are missing, let us know!
Also, any element you select in the elements tab will likewise be selected in the react tab.
