### ISSUE TITLE
React devtools 0.14.2 broken in Firefox Nightly

### ISSUE THREAD

**Issue by wldcordeiro** [facebook/react-devtools#260]
Currently if you install in Firefox Nightly there is no tab in devtools.

**Comment by ngyikp** [comment]
Confirmed that the version at Mozilla Add-ons is broken, but building manually from source works fine though, so it has been fixed.

<img width="1050" alt="screen shot 2015-10-16 at 11 54 40 am" src="https://cloud.githubusercontent.com/assets/6135313/10533512/be6c3ebc-73fc-11e5-80e8-af26923fe8c8.png">

**Comment by spicyj** [comment]
That's weird, I don't think we fixed anything here.

**Comment by ngyikp** [comment]
Maybe https://github.com/facebook/react-devtools/commit/ce487338bc5a50260ca023ea5845f59a246f2272 ?

**Comment by spicyj** [comment]
Yeah, probably that. Guess it's time for a version bump.

**Comment by wldcordeiro** [comment]
That'd be great! Also I'd suggest adding the xpi in the releases section like Ublock does so that people can install it before the Mozilla approval if they want to.

**Comment by spicyj** [comment]
New release, also submitted to the Chrome store and AMO. Waiting for review there though…

https://github.com/facebook/react-devtools/releases/tag/v0.14.4

**Comment by wldcordeiro** [comment]
@spicyj That's still not working for me.

**Comment by spicyj** [comment]
Hmm. I can't seem to get the tab to show up in nightly using that xpi or with `jpm run --debug -b /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin`…

**Comment by ngyikp** [comment]
Found the issue, turns out the reason it's working fine on my machine is because I just recently updated jpm and I got this fix: https://github.com/mozilla-jetpack/jpm-core/commit/e2bc229164dfcb37f3111950e536e3452bab646f

Which is documented on https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/

If I take the compiled version at https://github.com/facebook/react-devtools/releases/download/v0.14.4/react-devtools-0.14.4.xpi , patch in the updated bootstrap.js and repack it, then it works on Firefox Nightly again.

You can also try my self-compiled version: https://dl.dropboxusercontent.com/u/1286251/execs/newerjpm-react-devtools-0.14.4.xpi

In the end, update jpm :)

**Comment by wldcordeiro** [comment]
Nice find @ngyikp! Thanks for the XPI, that'll do till the official hits AMO.

**Comment by spicyj** [comment]
Thank you @ngyikp! I'll do a 0.14.5 with that.
