### ISSUE TITLE
About "Create Panel in Chrome"

### ISSUE THREAD

**Issue by Hi-Rube** [facebook/react-devtools#294]
https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/main.js#L57

when I use    

``` javascript
var loadCheckInterval = setInterval(function() {
  createPanelIfReactLoaded();
}, 200);
```

will create many React in devTool

**Comment by jaredly** [comment]
Are you saying the timeout should be lowered to `200` from `1000`?

**Comment by Hi-Rube** [comment]
@jaredly why should be 1000, 200 will be error

**Comment by jaredly** [comment]
Can you show a screenshot of the error?

**Comment by Hi-Rube** [comment]
![](http://7xntki.com1.z0.glb.clouddn.com/屏幕快照%202015-12-10%20上午3.24.23.png)

**Comment by jaredly** [comment]
Wow! That's exciting. What's your Operating system version, and what version of Chrome are you on?

**Comment by Hi-Rube** [comment]
osx 10.11， chrome  46.0.2490.86 (64-bit)

**Comment by kassens** [comment]
Weird, I've never seen this happen. Does this happen to you on every page that has react or is there something specific on your page? (You can try on facebook.com)

**Comment by Timothee** [comment]
I haven't figured out yet how to reproduce but I've just had the issue twice in a row. The first time I had more tabs than the second one shown here: 
![screen shot 2016-02-16 at 5 33 51 pm](https://cloud.githubusercontent.com/assets/159328/13097180/fc0809ee-d4d3-11e5-8741-92434ad77388.png)

OS X 10.10.5, Chrome 47.0.2526.111.

I'm using a local copy of the extension rather than the one from the store though… I'll try to see if I can find step to reproduce and update. But basically: me too.

**Comment by gaearon** [comment]
Can anyone still repro this?

**Comment by Timothee** [comment]
@gaearon I haven't seen the issue in a while.

**Comment by gaearon** [comment]
I'm going to close because it's very hard to tell how that code could even race. There's a boolean guard that gets set immediately.

So I can't solve this without seeing a reproducing case.
