### ISSUE TITLE
检查视图： 背景页 （无效）

### ISSUE THREAD

**Issue by iniestano8** [facebook/react-devtools#329]
![image](https://cloud.githubusercontent.com/assets/5787530/13201200/17e81c0e-d8a2-11e5-931f-3c38713e9d83.png)

**Comment by spicyj** [comment]
Sorry, I don't understand Chinese. Google translates this as "Check View: background page (invalid)".

What version of Chrome are you using? Have you tried removing and reinstalling the devtools?

**Comment by rayshan** [comment]
I'm not sure what @iniestano8 is trying to say. The title of the issue is basically the same as the line he highlighted, and it says:

![screen shot 2016-03-09 at 8 46 32 pm](https://cloud.githubusercontent.com/assets/3760840/13659615/0e277ed2-e638-11e5-8fc8-f88d5181bd26.png)

This is for Chrome extension development, it says inactive because user hasn't used React DevTools in a while. Clicking on the link it will make it active.

**Comment by kassens** [comment]
I have seen this, but didn't see any negative effects from it, I think it just re-activates when the devtools are focused again. Please comment with more details in case this is a problem!
