### ISSUE TITLE
not work when web page use react 0.15

### ISSUE THREAD

**Issue by p2227** [facebook/react-devtools#357]
for example https://facebook.github.io
can't detect the components

**Comment by tgoldenberg** [comment]
I'm using `15.0.1` on meteor and Devtools does not work as well

**Comment by zpao** [comment]
What version of the devtools and browser are you using? Everything appears to be working for me in Firefox and Chrome.

**Comment by tgoldenberg** [comment]
React Devtools `Version: 0.14.9`, Chrome `Version 49.0.2623.112 (64-bit)` @zpao

**Comment by tgoldenberg** [comment]
Also @zpao, strangely it works if I go to https://facebook.github.io/react/ and inspect, but my Meteor app doesn't render. Also positive this is due to version bump, since it was working fine previously

**Comment by p2227** [comment]
strangely it works now -_-|||

**Comment by tgoldenberg** [comment]
@zpao So I finally got Devtools working, and I think the reasons for it not working should be looked into. There were 2 things causing Devtools not to work in my app
1. I was initializing Bootstrap.js from within my main component
2. I was initialing Tawk.io from within my main component

The second of these was necessary since Tawk depends on the user's name / email. As for Bootstrap, we are using v4, and the only way I have been able to get it to work is to wrap the bootstrap.js in a function, export it, and invoke and the first `componentDidMount`. 

These were working fine for me before bumping up to React v15, so I'm not sure if these might be issues for other users.

**Comment by AaronHarris** [comment]
I don't use bootstrap or tawk, but I can add to that I have found react devtools breaking after upgrading to v15.0.1 (it only breaks when I open React devtools)

**Comment by virtyaluk** [comment]
The same for me too.
React `15.0.2`, React Developer Tools `0.14.10`, Chrome `53.0.2746.0 canary (64-bit)`.

**Comment by spicyj** [comment]
Can someone post a link to a page that consistently reproduces the problem?

**Comment by virtyaluk** [comment]
There's no some specific issue. There's no an issue at all. It's just won't start. Once I get up my local react project, RDT stays inactive no matter what I do. There're no errors in console. There's nothing at all.

**Comment by eschaefer** [comment]
Had the same issue as https://github.com/facebook/react-devtools/issues/357#issuecomment-209419266, but it just randomly started working again. Was trying to set up an example URL, and it just kind of resolved itself.

**Comment by muffinresearch** [comment]
Using React 15.1.0 we are seeing the same problem in a universal app where it used to work. 

Disabling server-side rendering (SSR) makes it work. Would be better if it worked without needing to disable SSR, though we're still investigating if it's something caused by a React update or a change our end.

**Comment by spicyj** [comment]
No one has posted a link that reproduces the problem so this is totally unactionable for us. If anyone does, we can look into this.
