### ISSUE TITLE
Missing component names

### ISSUE THREAD

**Issue by mrjoes** [facebook/react-devtools#4]
Is there any reason why component names are always "Unknown"?

Just in case, I'm using browserify and sources are not minified, only concatenated.

Here's how it looks like:
![image](https://f.cloud.github.com/assets/179880/1842226/ba428f80-74b7-11e3-8d2c-f5bb279ceca8.png)

**Comment by fresh5447** [comment]
I am using the chrome plugin [`React Developer Tools`](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) and when I inspect the React tree I see 'Proxy Component' instead of the components actual name. Might be a `webpack` issue? I tried adding 'displayName' and that didn't do it.

Anyone else run into this issue?
