### ISSUE TITLE
React tab doesn't show up in Firefox dev tools

### ISSUE THREAD

**Issue by manV** [facebook/react-devtools#434]
React tab doesn't show up(tried on both reactjs website and facebook.com). Firefox version 48.0 running on Ubuntu Gnome 16.04

**Comment by scoobster17** [comment]
This has been happening for me in Chrome too, build 53.0.2785.101 is the one I'm currently running on this machine (personal), but have tried on other machines (work) and had the same issue.

This includes "normal" Chrome, and Chrome Portable version, and I have tried removing the extension and re-installing.

Have used this tool before in the same browser(s)/machine(s) on projects previously, notably during September 2016 and did not have an issue with this appearing. I would have guessed it has regressed since a previous release, although looking at the releases page it seems the last one was in March, unless there has been a patch?

**Comment by herodrigues** [comment]
It does not show up for me in Chrome too.

Build 54.0.2840.71

**Comment by gaearon** [comment]
@herodrigues 

If it doesn't show up in Chrome, there may be two reasons:

1. The website you're on doesn't actually use React (or uses a very old version)
2. The React code is inside of an iframe ([then there is a workaround](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools))

**Comment by herodrigues** [comment]
Thanks for answering, @gaearon! None of these options works because I'm using ReactDOM with a Chrome extension that is inside a ShadowDOM element.

**Comment by gaearon** [comment]
@herodrigues Can you confirm standalone DevTools still doesn't work inside a Chrome extension? I haven't verified this yet.

**Comment by herodrigues** [comment]
Yes. Here I'm using *create-react-app*. As you can see, React tab shows up in DevTools inspector.

![image](https://cloud.githubusercontent.com/assets/1832537/22991669/dc65db10-f39b-11e6-82b3-eb5d49acff2c.png)

It doesn't show up when developing my Chrome extension though.

**Comment by gaearon** [comment]
Sorry, I was referring specifically to *standalone* DevTools.
I linked to it from my comment above:

https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

Does this approach work for you, or is it also broken?

**Comment by herodrigues** [comment]
For some reason, it didn't work in the first time. Not sure if it was because I placed ```js import 'react-devtools'``` before ```js import 'react'```.

![image](https://cloud.githubusercontent.com/assets/1832537/22992130/7c11a440-f39d-11e6-9574-007df70020eb.png)

- index.js (content script in manifest.json)

```js
import React from 'react';
import 'react-devtools';
import ReactDOM from 'react-dom';
import Root from './containers/Root';

window.addEventListener('DOMContentLoaded', function () {
  const container = document.createElement('div');
  container.id = 'main-container';
  document.body.appendChild(container);

  ReactDOM.render(
    <Root />,
    document.getElementById('main-container')
  );
});
``` 

That's really awesome!

**Comment by gaearon** [comment]
I'm glad it helps!

**Comment by gaearon** [comment]
Closing for lack of specifics.
