### ISSUE TITLE
No tab shown in chrome

### ISSUE THREAD

**Issue by alexbaulch** [facebook/react-devtools#445]
After installing, enabling and checking both 'Allow in incognito' and 'Allow access to file URLs' but no tab shows up. I have tried disabling all the other extensions but there was no change.

It appears that I am not the only person experiencing this, there are comments which mirror my experience on the chrome extension store. https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi/reviews.

I am on a PC, running Windows 7, in Chrome Version 52.0.2743.116 m (64-bit).

**Comment by DaveLindberg** [comment]
+1 

Running Chrome Version 54.0.2840.71 (64-bit) on macOS Sierra v 10.12.1. Worked fine a couple weeks ago.

**Comment by DuhSokola** [comment]
+1

**Comment by DaveLindberg** [comment]
Clarification: I see that react devtools _does_ work properly when working on a project bootstrapped with Create React App.  But if I create a new js file, import react and react-dom, the tool won't display. Hope this helps.

**Comment by etiology** [comment]
+1

 - Chrome version 54.0.2840.71 (64-bit)
 - OSX 10.11.6
 - React Dev Tools 0.15.4

**Comment by shixukai** [comment]
+1

**Comment by carvinlo** [comment]
+1

**Comment by aep** [comment]
Google Chrome 54.0.2840.100 
linux 64

**Comment by cochranjd** [comment]
+1

Version 55.0.2883.95 (64-bit)
OSX 10.11.6

**Comment by eagyne** [comment]
Maybe you have visit the web site which is not dev by react .try to visit https://www.instagram.com/ and open the devtool again and you should see the React tab.

**Comment by DaveLindberg** [comment]
Resolved here on Chrome Version 55.0.2883.95 (64-bit)

:-)

**Comment by clock21am** [comment]
hi, is this issue is fixed ?

**Comment by gaearon** [comment]
I created `index.js`:

```js
var React = require('react')
var ReactDOM = require('react-dom')

ReactDOM.render(React.createElement('h1', {}, 'Hello'), document.body)
```

Then I installed `webpack`, `react`, and `react-dom`.
I added a webpack config:

```js
module.exports = {
  entry: './index',
  output: {
    filename: 'out.js'
  }
}
```

I ran `webpack` and created an HTML page:

```js
<html>
  <body>
  </body>
  <script src="out.js"></script>
</html>
```

It shows up in DevTools:

<img width="717" alt="screen shot 2017-02-15 at 19 30 01" src="https://cloud.githubusercontent.com/assets/810438/22991714/2d5f7d6e-f3b5-11e6-886c-b721e0cb8d96.png">

I don't know what the problem is, but it seems to work, so I'm assuming it was some bug on Chrome side that got fixed at some point.

If you can reproduce the problem please provide an example project.
