### ISSUE TITLE
Feature: Select an element on the page to inspect it 

### ISSUE THREAD

**Issue by mavericken** [facebook/react-devtools#466]
It should be possible to click on a component in the page to find it in React Devtools.  To me it seems like the most obvious suggestion possible so I was shocked when I looked through the issue list twice and did not see it.  Maybe the feature exists and I just can't find it...
![image](https://cloud.githubusercontent.com/assets/7833752/21506180/1bc5cf86-cc3c-11e6-9083-c1eec8de63be.png)

**Comment by mavericken** [comment]
While not super intuitive... I should have seen that in the readme.  Thanks @ngyikp

**Comment by roryokane** [comment]
Despite the existence of that method in the README, I  think that a “Pick an element” button for the React tab would still be a good feature to have, and that this issue should stay open.

The method in the README is very hard to discover just from using the extension. Picking an element from the page was the first thing I tried to do after installing the extension, but when I saw no interface for it, I just assumed that the extension didn't support that feature. And when installing this extension [from the Firefox add-ons directory](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/), the README that contains those instructions is never shown.

While the easiest way to implement element picking would probably be adding a button as in @mavericken’s mockup, an even better interface, if possible, would override the existing “Pick an element” button. When using it from the React tab, you should stay on the React tab afterwards, but from any other tab, you should go to the Elements (in Chrome) or Inspector (in Firefox) tab like normal. One possible way of implementing this would be letting it switch you to the Elements/Inspector tab as normal and then immediately triggering a switch to the React tab, which would load the selected element using the existing functionality.

If the global button were overridden in that way, not only should selecting an element in Elements/Inspector and then switching to React select the correct element in React, but the other way around should also work: selecting an element in React and switching to Elements/Inspector should select the correct element in Elements/Inspector. This would prevent someone having to select the same element twice if they forgot what tab they were in.

By the way, due to some bug, the tab-switching method described in the README doesn't work at all for me, using Firefox on Ubuntu. (The file that tries to implement it for Firefox is [`trackSelection.js`](https://github.com/facebook/react-devtools/blob/5fedf871df064bbde429c27eddead08cabe72168/shells/firefox/main/trackSelection.js).) The lack of a workaround makes me desire a dedicated button even more.

**Comment by mavericken** [comment]
I still think it would be a nice feature, also.  I'll reopen for now, @roryokane.

**Comment by gaearon** [comment]
Tagging this as a good contribution opportunity. We already have the ability to highlight React components—we do that on hover. So I imagine it should be possible to do it the other way around, although I don’t know how.

**Comment by ngyikp** [comment]
This is fixed at https://github.com/facebook/react-devtools/pull/729, this issue can be closed
