### ISSUE TITLE
[Feature request] Request for Select All feature and React component hierarchy visualizer 

### ISSUE THREAD

**Issue by broyda** [facebook/react-devtools#474]
In debugging fairly large deeply nested component hierarchies, I felt it would be great if we have two additional features available in a future version (browser extension or app) of the React devtools:

1. Ability to do a "select all" and copy React component data from the 'React' tab in browser dev tools for any offline analysis.

2. A component hierarchy tree diagram (can be a separate panel within the React tab - the root at the top and the child components arranged vertically below the root) - a few other ideas are: on click of any node in this tree, the focus automatically shifts to the relevant node in the React components view.

**Comment by gaearon** [comment]
Thanks for the suggestions! These are interesting, but it's very hard to turn these into actionable items for us. If you have a design in mind, and are ready to contribute a proof of concept, I would love to see it. Otherwise I appreciate the ideas, but will close because it is not very actionable right now.
