### ISSUE TITLE
It's useless on the lastest Chrome (56.0.2924.87)

### ISSUE THREAD

**Issue by youmyyou** [facebook/react-devtools#496]

**Comment by gaearon** [comment]
Can you explain what "useless" means? Is something broken?

**Comment by gaearon** [comment]
I just downloaded the latest Chrome:

<img width="395" alt="screen shot 2017-02-08 at 14 03 44" src="https://cloud.githubusercontent.com/assets/810438/22740389/72dc89bc-ee07-11e6-92c8-7d8b7afdc923.png">

I also installed the latest version of React DevTools:

<img width="663" alt="screen shot 2017-02-08 at 14 04 30" src="https://cloud.githubusercontent.com/assets/810438/22740406/893e46b4-ee07-11e6-9ed5-3206beffbe26.png">

I went to https://facebook.github.io/react/ and verified that React tab shows up:

<img width="815" alt="screen shot 2017-02-08 at 14 05 15" src="https://cloud.githubusercontent.com/assets/810438/22740430/a500b6c0-ee07-11e6-8d93-38e725bfd952.png">

Since there are no other details, I think the problem may be due to some misunderstanding of how the extension works. I’m going to close but feel free to comment if you still have issues. If you can provide a way to reproduce I’ll be happy to take a look!

**Comment by youmyyou** [comment]
<img width="836" alt="2017-02-08 11 51 58" src="https://cloud.githubusercontent.com/assets/7312939/22744915/cbd27106-ee59-11e6-8981-20efbc4fbe7d.png">
<img width="218" alt="2017-02-08 11 52 29" src="https://cloud.githubusercontent.com/assets/7312939/22744928/d317706a-ee59-11e6-8bfe-16bc2a37de2c.png">
<img width="673" alt="2017-02-08 11 52 46" src="https://cloud.githubusercontent.com/assets/7312939/22744933/d667bdd8-ee59-11e6-84e6-6e30feb49caa.png">
Just like you,but mine is not working.

**Comment by gaearon** [comment]
The React tab will only appear on websites using React. Are you testing on one?

**Comment by youmyyou** [comment]
Thank you! I know what's wrong. I create a http server to test and it appeared.

**Comment by gaearon** [comment]
👍
