### ISSUE TITLE
Send only changed fields for updates

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#531]
I think there might be some relatively low hanging fruit in perf improvements.

In particular, whenever something changes, we [create a new data object](https://github.com/facebook/react-devtools/blob/d4a10cf9949f76816c594fbfe814e37582e6ee4d/backend/attachRenderer.js#L125-L130) with [all these properties](https://github.com/facebook/react-devtools/blob/d4a10cf9949f76816c594fbfe814e37582e6ee4d/backend/getData.js#L115-L129) even if only one of them has changed. Some of them don't even change at all (e.g. type and name).

We also [do the same](https://github.com/facebook/react-devtools/blob/d4a10cf9949f76816c594fbfe814e37582e6ee4d/backend/attachRendererFiber.js#L97) in Fiber version.

I think we should avoid sending fields that haven't changed. This would reduce how much data goes over the bridge and potentially make updates with DevTools open faster.

Potential pitfall (I think we can address this *after* there's a working proof of concept): Fiber version might need some extra code to make sure we're dealing with current props. This becomes an issue if `updater` doesn't change on every single update, and thus may be bound to the wrong Fiber. Don't worry if you don't understand it.

**Comment by rajpatel507** [comment]
@gaearon  I didn't understand much, but still i want to work on this issue. can you help me with this?

**Comment by gaearon** [comment]
I could try, what kind of help do you need?
The post above has some starting points, do you have specific questions about them?

**Comment by rajpatel507** [comment]
What i understood from first two paragraph is, property that din't change should not be there in return statement.
I am bit confuse over how to find if property is changed or not ?

**Comment by gaearon** [comment]
I think it's fine to keep it in the return statement.
We could filter the data later somewhere.

I don't have specific suggestions about where to do that—the easiest way to find out is for you to try to make it work and then we can discuss if that approach works well or not.

**Comment by nanot1m** [comment]
Is there any way to obtain fields that were before changes? It seems like Reconciler do not pass no info about previous state of element which was changed

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
