### ISSUE TITLE
[Feature Request]: Better component inspecting?

### ISSUE THREAD

**Issue by DarrylD** [facebook/react-devtools#563]
Possibly leverage [component-inspector](https://github.com/lahmatiy/component-inspector). Seems like a more natural way of handling inspecting. [Made a query there also](https://github.com/lahmatiy/component-inspector/issues/26)

![Example for React](http://s63.imgup.net/ci-introcbc0.gif)

**Comment by gaearon** [comment]
This is a bit of an open-ended issue. It’s hard for me to tell what exactly you are proposing, which features you’re interested in, and how that integration would work. Since there’s more context in https://github.com/lahmatiy/component-inspector/issues/26 let’s just keep the discussion there, and if there are more specific proposals for this repo, I’ll be happy to hear them!
