### ISSUE TITLE
State of Connect object occurs empty with react-redux 5.0.3

### ISSUE THREAD

**Issue by Jacksing** [facebook/react-devtools#570]
The state property occurs Empty object while working with following packages.
    - react@15.4.2
    - redux@3.6.0
    - react-redux@5.0.3
by running the redux example [reactjs redux example todos](https://github.com/reactjs/redux/tree/master/examples/todos)

![state_empty](https://cloud.githubusercontent.com/assets/7564447/23490495/d7ee1c02-ff33-11e6-93c0-144cb705d3c9.png)

After switch react-redux to a lower edition such as @4.4.6 in my situation, the state returns back.

![state_return](https://cloud.githubusercontent.com/assets/7564447/23490790/641a71a2-ff35-11e6-8815-aefd64f0a69c.png)

Maybe this is not caused by react-devtools but them together are working with some little issue now.

**Comment by gaearon** [comment]
This looks like an [intentional decision](https://github.com/reactjs/react-redux/blob/ff33f0ccce447413e820140648267a6b8fe1484d/src/components/connectAdvanced.js#L218) by React Redux maintainers. I’m not maintaining it anymore so I can’t really comment on that. Please bring it up in the React Redux repo if you’re interested in reasons. Cheers!
