### ISSUE TITLE
Electron shell data transfer is lossy

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#582]
Since Electron shell uses JSON as transfer format, it loses some data, such as `undefined` values in objects, and sparsity of arrays. See my comments in https://github.com/facebook/react-devtools/pull/536#issuecomment-285235927.

I'm not sure how to solve this but it is confusing to have this disparity between shells.

**Comment by gaearon** [comment]
Maybe we should use something like https://github.com/cognitect/transit-js instead of JSON as transport?

**Comment by tomaszlakomygp** [comment]
transit-js is quite a lot of code (10K gzipped), maybe there's something smaller that can be used to achieve the same effect?

**Comment by gaearon** [comment]
Does it really matter though, if it’s only inside DevTools?

**Comment by tomaszlakomygp** [comment]
Not really, those are my web development habits speaking 😄

**Comment by jaredly** [comment]
yeah, transit could be a good thing to do

**Comment by davidfurlong** [comment]
@gaearon 
Took at a look at transit-js & using it here.
Potential issues with it:
- https://github.com/cognitect/transit-js/issues/10 (I.e. converts undefined to null)
- It converts Objects into its own type of objects, and parsing them back to plain JS objects requires nested calls of http://cognitect.github.io/transit-js/classes/transit.html#methods_transit.mapToObject 

Are there any alternatives people know of?

**Comment by gaearon** [comment]
Interesting. I am not aware of alternatives but I'm fairly sure somebody must have solved this problem before.

**Comment by davidfurlong** [comment]
Theres also http://msgpack.org/ but that seems to be more concerned with compression than with consistency across null/undefined/NaN

**Comment by davidfurlong** [comment]
Okay I've modified the JSON2 parse and stringify functions to support undefined, NaN, Infinity, -Infinity. They were omitted from JSON because they are references to their global respectives (I think properties of the Number type) and hence aren't expressions, but references. I think disregarding the security problems/ spec will work for our use case.

https://github.com/davidfurlong/JSON-js

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
