### ISSUE TITLE
Failed to eval: Cannot read property 'scrollIntoView' of undefined

### ISSUE THREAD

**Issue by robinkam** [facebook/react-devtools#594]
Hi, when I use Nuclide React Inspector to debug my react native app on iOS simulator, I always got the error "Failed to eval: Cannot read property 'scrollIntoView' of undefined" in the red screen.
The debugger suggested the exception point was located around the source code below: 

`scroll: isReactDOM && "function" == typeof window.document.body.scrollIntoView,`

The debugger indicated the `window.document.body` was undefined.

However I tried some other react native apps which were much simpler, everything worked well.

Is there something wrong with my code? But my app worked well when not using Nuclide React Inspector to debug. No warnings or errors at all.

The  inspector tool is very useful, but this annoying issue is blocking me from using it and driving me mad. Please help and give some workarounds. Thanks!

**Comment by olofd** [comment]
@robinkam Same here. A bit older project and this happens all the time. Even though I've updated to latest RN.

**Comment by gaearon** [comment]
Please provide a minimal project reproducing the issue. 😉 
Otherwise how could we diagnose it?

**Comment by gaearon** [comment]
If you look at the [source code](https://github.com/facebook/react-devtools/blob/c4be954d216888e57eb921004d2651e154809c19/agent/Agent.js#L117) (I just searched for the variable name you provided), you will see the check:

```js
var isReactDOM = window.document && typeof window.document.createElement === 'function';
```

So if you have this issue, it means both `window.document` and `window.document.createElement` exist in your RN project.

I tried the UIExplorer example in React Native repo, and it doesn’t seem to have them defined:

<img width="478" alt="screen shot 2017-04-20 at 1 20 21 pm" src="https://cloud.githubusercontent.com/assets/810438/25230524/364f4e7e-25cc-11e7-8931-10016af70111.png">
<img width="89" alt="screen shot 2017-04-20 at 1 20 25 pm" src="https://cloud.githubusercontent.com/assets/810438/25230525/36501d68-25cc-11e7-9ff5-bae2abd2f265.png">

So the issue is likely with some third party library you’re using (or your code) that adds `window.document` and thus confuses the DevTools. You can probably `console.log(window.document)` to get a sense for where it’s coming from.

I hope this helps! I’ll close as not an issue in this repo, but if you think it’s a bug please provide a reproducing project.

**Comment by tianjyan** [comment]
Hi Team, I am using [jitsi-meet](https://github.com/jitsi/jitsi-meet) and also get this error. jitsi-meet uses jQuery and will set `window.document` and `window.document.createElement`. This will confuse the DevTools. So I have a question should we use libs that heavily rely on HTML DOM in React Native ? It is pleasure if you can give me some suggestions. Thank you.
