### ISSUE TITLE
Refactor split pane bugfix to avoid magic numbers

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#615]
See https://github.com/facebook/react-devtools/issues/611 and https://github.com/facebook/react-devtools/pull/614.

I’d like to avoid magic numbers, and instead properly fix it. (Maybe we should read something from the right pane DOM node directly.)

**Comment by shriah** [comment]
I have created a pull request for this that introduces a wrapper element that has no padding or margin and it contains the dragger and the right pane. This way we can set the width or height to the wrapper without worrying about the padding and margin of the children.

We needed a magic number before because we set the width of the right pane but the width we calculated was for the dragger and the right pane.
