### ISSUE TITLE
webpack command isn't found when following shell/chrome/readme instructions

### ISSUE THREAD

**Issue by clarkbw** [facebook/react-devtools#647]
Filing some issues as I get started.  Apologies if I have some setup issue here.  I know some people have path tricks to get the local `node_modules/.bin/` added into their PATH but I'm not even sure that would work in the current directory setup.

From the [Chrome shell README](https://github.com/clarkbw/react-devtools/blob/master/shells/chrome/Readme.md#the-chrome-plugin)

The `webpack` command doesn't run for me because I don't have it globally installed and it doesn't seem to be in my path.

Step 2 in hacking is to run `webpack --config webpack.backend.js` however I don't have `webpack` in my path.  The package has been installed (via the previous `npm install`) locally two folders up so I can run `../../node_modules/.bin/webpack` to get the version of webpack I believe is expected.

I guess if it works for you running `which webpack` could reveal what version of webpack you're running and where it is located.

- [ ] I could change the docs to reflect the location of webpack but that location is not very friendly to windows users.  
- [ ] I could add a couple scripts to the [package.json](https://github.com/clarkbw/react-devtools/blob/master/package.json) file which would run things with some npm commands.  I would expect something like `npm run chrome:webpack:config` and then `npm run chrome:webpack:watch`. This is usually my preferred method but you don't seem to have a lot of [scripts](https://github.com/clarkbw/react-devtools/blob/master/package.json#L30-L35) so perhaps that's not the style of this repo.

Let me know and I can make a PR.

**Comment by gaearon** [comment]
Yes, these instructions are from two years ago when nobody knew how to use npm scripts. Sorry 😞 

Ideally this would all be done via npm scripts. I'm using `./build.sh` in the same directory but it’s also bad because it doesn’t work on Windows.

If you could convert build scripts to use npm scripts (and explicit Node scripts when necessary) that would help.

I think @Tushkiz started working on this in https://github.com/facebook/react-devtools/pull/632 so maybe you could join efforts.

**Comment by clarkbw** [comment]
Thanks @gaearon! Looks like #632 is a good place to build off of.

**Comment by clarkbw** [comment]
This was fixed by #802
