### ISSUE TITLE
Feature Request: Perf buttons

### ISSUE THREAD

**Issue by AsaAyers** [facebook/react-devtools#71]
It would be really nice if this extension had buttons that called out to `React.addons.Perf.start()` / `React.addons.Perf.stop()` / `React.addons.Perf.print*()`

**Comment by mfunkie** [comment]
:+1: This would be fantastic.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment]
This is on our radar. Looking into some great perf integration in the devtools

**Comment by Anahkiasen** [comment]
:+1: Would love this

**Comment by albertogasparin** [comment]
No further update on this? It would be really handy

**Comment by crysislinux** [comment]
Hi everyone and @albertogasparin.

I have built a chrome devtools extension to achieve this.

link: https://github.com/crysislinux/chrome-react-perf

**Comment by aight8** [comment]
+1

**Comment by martin-svk** [comment]
+1

**Comment by sicdigital** [comment]
+1

**Comment by ruanmer** [comment]
+1

**Comment by marob** [comment]
@crysislinux: thanks!
@jaredly & @crysislinux: having a unique/official extension would be great. Is it conceivable to port the chrome-react-perf code to the react-developer-tools?

**Comment by crysislinux** [comment]
@marob I am not sure about that. But I will try to dig into react-developer-tools.

BTW. Do people still want this feature? If yes. I will start work on this.

see https://github.com/crysislinux/chrome-react-perf/issues/14

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
