### ISSUE TITLE
Documentation on using the plugins

### ISSUE THREAD

**Issue by mmahalwy** [facebook/react-devtools#711]
Is there any documentation about this? How can someone setup the relay plugin for example?

**Comment by banderson** [comment]
I am very curious about this too. I was considering writing a plugin to _decorate_ some components in the tree for a component library, but it seems like this is an internal concept and not intended for non-core members to use, is that right? Just trying to save myself time if that's the case.

**Comment by fletcher91** [comment]
Being able to add an object to the right panel (props, state, context, <pluginthingy if applicable>) would be awesome.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
