### ISSUE TITLE
Add checkboxes to RN style editor to toggle styles

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#795]
They should toggle styles, just like Chrome does.

**Comment by sumnerevans** [comment]
@gaearon is this style editor what you are referring to?
<img width="274" alt="screen shot 2017-07-05 at 13 01 23" src="https://user-images.githubusercontent.com/16734772/27880465-4be7d26e-6182-11e7-9ab8-e72a581564d3.png">

**Comment by holmes2** [comment]
@gaearon I would like to work on this and so just needed to confirm that are we talking about this

**Comment by bvaughn** [comment]
That's correct @holmes2. Dan is saying that React DevTools should have a similar function as Chrome DevTools does:

![screen shot 2017-09-07 at 8 46 54 am](https://user-images.githubusercontent.com/29597/30172250-2081a132-93a9-11e7-9b09-d9ee1bb87bc6.png)

**Comment by holmes2** [comment]
is there a place i can ask my doubts while i am trying to solve this feature ? Or should I ask in the github pull request itself ?

**Comment by bvaughn** [comment]
GitHub is probably the most centralized place for questions like that.

**Comment by shahzeb1** [comment]
Is this an issue that still needs a PR @bvaughn?
It hasn't been touched for a couple of years.

**Comment by bvaughn** [comment]
Nah. I wouldn't suggest putting together a PR for this repo at the current time. Wait for us to  get RN support in the new DevTools, then we can focus our efforts there.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
