### ISSUE TITLE
Feature proposal: Command Panel integration

### ISSUE THREAD

**Issue by piperchester** [facebook/react-devtools#808]
Mainly wanted consensus from the community - is it feasible to integrate with the "Command Panel" feature of DevTools, visible through `cmd+shift+p`?

I'm not sure if that integration's exposed for developers, but was wondering what the core maintainers' thoughts are 😄 I'd be willing to work on it 🔧

**Comment by bvaughn** [comment]
The [release announcement for the "Command Menu" feature](https://developers.google.com/web/updates/2016/04/devtools-digest-command-menu?hl=en) makes no mention of customization. I've searched the API docs and other Google developer posts looking for any mention of an API for adding custom entries to this menu as well and haven't found anything. At this time, I'm under the impression that it isn't possible.

I'm going to close this issue for now because I don't believe it's actionable. If you know of (or can find) a way to add React DevTools to the Command Menu please re-open the issue and we'll be happy to consider it!

**Comment by piperchester** [comment]
Totally fair! Appreciate the research and thorough response. Thanks!
