### ISSUE TITLE
message event sent when devtools are opened.

### ISSUE THREAD

**Issue by arshdkhn1** [facebook/react-devtools#812]
Hi,

I have setup a message event handler that parses the data sent via message event in my app. Whenever I open react devtools it fires many message events whose source is sometimes `Window` and it looks like - 
![screenshot 2017-06-14 18 23 06](https://user-images.githubusercontent.com/16819670/27133090-a8e59122-512e-11e7-90d8-879cd327e935.png)

Right now I am blocking these message event by doing this - 
```js
if((/^react-devtools/gi).test(e.data.source)) {
return;
}
```
I wanted to know why these message event are being sent and what it is the best way to block these event. I get these message events in both firefox and chrome.

Thanks.

**Comment by bvaughn** [comment]
DevTools backend and content scripts talk to each other via `window.postMessage`. These messages are tagged with a `source` that's either "react-devtools-bridge" or "react-devtools-content-script". DevTools uses this to filter _all but its own messages_ (see [`backend.js`](https://github.com/facebook/react-devtools/blob/3a0b82ad1b9c68afd560e18bc57f814ab58b41fe/shells/chrome/src/backend.js#L37) and [`contentScript.js`](https://github.com/facebook/react-devtools/blob/3a0b82ad1b9c68afd560e18bc57f814ab58b41fe/shells/chrome/src/contentScript.js#L37)).

Maybe you could use a similar approach in your application/extension to ignore messages from other extensions?

I'm going to close this issue since it doesn't seem very actionable. 😄

**Comment by arshdkhn1** [comment]
@bvaughn  thanks. 
But can you elaborate a bit more on this -
> Maybe you could use a similar approach in your application/extension to ignore messages from other extensions?

**Comment by bvaughn** [comment]
I thought I did elaborate above :smile: I was suggesting you could do a similar thing as React DevTools does: tag your messages with some unique identifier and then filter out any messages not containing your unique identifier (a whitelist).

**Comment by arshdkhn1** [comment]
@bvaughn hmm, yes you did elaborate it above. thanks again.

**Comment by bvaughn** [comment]
No worries 🤣 I thought maybe my explanation just didn't make sense.
