### ISSUE TITLE
Firefox: update icon when browsing away from a React site

### ISSUE THREAD

**Issue by fvsch** [facebook/react-devtools#823]
This seems to be a separate problem from #650.

With the Firefox extension (2.3.3), a "React" tab is added to the developer tools and is shown for all pages, whether they use React or not. It’s a bit noisy if you’re not a React developer for 90% of your time. :)

Ideally, this tab would show up only when React is detected on the page. This seems to be how it works in Chrome.

If it requires a specific logic for Firefox, maybe it could be poached from what the [Vue.js DevTools](https://github.com/vuejs/vue-devtools) extension does.

**Comment by bvaughn** [comment]
The next release of DevTools will update the Firefox plugin to be a WebExtension rather than an add-on. Once this has been done, the DevTools tab will only be shown (initially) if the current tab uses React- the same way Chrome works.

Unfortunately the issue described in #650 still occurs for Firefox. In addition to that, Firefox also fails to update the icon when you browse away from a React site (to a non-React site). This may be due to a missing API in Firefox. I'm not sure yet.

I'd like to repurpose this issue to be about.

**Comment by fvsch** [comment]
@bvaughn Thanks for the info.
I’m okay with either repurposing this issue or closing and opening a new one.

**Comment by bvaughn** [comment]
It's okay. I'm on it. 😄

**Comment by bvaughn** [comment]
Fixed the Firefox-specific portion of this issue via #824
