### ISSUE TITLE
Browser toolbar icon has ugly greyish background in Firefox

### ISSUE THREAD

**Issue by jnachtigall** [facebook/react-devtools#850]
![react-devtools-icon](https://user-images.githubusercontent.com/3307404/28212446-ae8269cc-68a1-11e7-8a37-9c9f28511c6e.png)

I guess the background of this icon should be transparent. FWIW, I am using Firefox with its dark developer edition theme.

**Comment by tylercrompton** [comment]
Instead of opening a new issue, I figured that asking here would be a better choice. What exactly is the purpose of the toolbar button. It doesn't seem to have any functionality other than telling me which build that I'm using and that I can use this add-on via the developer tools. Surely I am missing something. How is the button necessary?

**Comment by bvaughn** [comment]
> It doesn't seem to have any functionality other than telling me which build that I'm using and that I can use this add-on via the developer tools.

This is a pretty important piece of information. Before we added the new icons, there was a widespread problem of sites accidentally using a development build of React for a production instance (see facebook/react/issues/8784). This caused unnecessary slowness due to larger bundle size and development-only validations being run. The custom icon was crucial in raising awareness about this- essentially mobilizing all React developers to help identify such sites and get them migrated to production mode.

All of this being said, you're free to hide the toolbar icon (right-click -> "hide in chrome menu") if you don't see personal value.

**Comment by tylercrompton** [comment]
Ah. I never considered that that would be an issue. Thank you for the insight.

**Comment by jnachtigall** [comment]
@bvaughn FWIW, I still see this "ugly" non-transparent background in Firefox:

On websites **without** react, there's a light greyish background:

![2017-10-04 09_39_22-release notes_ 1 16 1 webdevprototyp visual studio code](https://user-images.githubusercontent.com/3307404/31165416-4ef76658-a8eb-11e7-84f3-07d16b672880.png)

On website **with** react, the background is dark greyish:
![2017-10-04 09_40_04-gesendete elemente - jens nachtigall init de - outlook](https://user-images.githubusercontent.com/3307404/31165417-4efce39e-a8eb-11e7-9229-c20b2143e976.png)

Also in the browser devtools tab, there's a slight dark background:
![2017-10-04 09_40_41-react - a javascript library for building user interfaces - nightly](https://user-images.githubusercontent.com/3307404/31165418-4eff4292-a8eb-11e7-84b1-48ae3e5193f0.png)

Compare to the other icons in the screenshots.

In all cases I think the icon's background should be transparent.

Maybe this issue could be re-opened?
