### ISSUE TITLE
This tool dose not support chrome extension pages

### ISSUE THREAD

**Issue by JHanLu** [facebook/react-devtools#874]
I'm currently developing a react chrome extension, but it seems like this tool doesn't support chrome extension developing at all.

**Comment by ngyikp** [comment]
> If your app is inside an iframe, a Chrome extension, React Native, or in another unusual environment, try the standalone version instead.

See https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

**Comment by herodrigues** [comment]
@JHanLu it does work with Chrome extensions. See https://github.com/facebook/react-devtools/issues/434#issuecomment-280116615

I also have a working example [here](https://github.com/herodrigues/refluxme)

**Comment by JHanLu** [comment]
@ngyikp Thanks! Problem solved

**Comment by JHanLu** [comment]
@herodrigues Thank you for your answer. But sadly i don't really understand your article.

**Comment by herodrigues** [comment]
@JHanLu That's sad. It's really detailed. 
Anyway, just look my https://github.com/facebook/react-devtools/issues/434#issuecomment-280116615 and you'll understand how to integrade react-devtools with your extension.

**Comment by dagumak** [comment]
@herodrigues The link to your website (http://herodrigues.me/javascript/2017/03/15/small-chrome-extension-react-flux/) says nothing relevant to react-devtools.

**Comment by herodrigues** [comment]
@dagumak The title of this issue is _This tool does not support chrome extension pages_. so the article is about a project that actually shows react-devtools working in a Chrome extension, though the focus of the article is how to use Flux/ReactJS in a extension.

What else do you want? My comment answers the question and I also have a project that uses react-devtools. See the project and you'll understand how to use it.
