### ISSUE TITLE
NaN state values are displayed as null

### ISSUE THREAD

**Issue by d07RiV** [facebook/react-devtools#956]
I'm trying to debug incorrect behavior in my app, and ran across this issue when trying to check my component state in dev tools. As seen on the left, it reports `childSizes[1].flex` to be `null`, when in reality it is `NaN`. Also, it doesn't show undefined values.

![image](https://user-images.githubusercontent.com/3448203/34382094-a9164d24-eb1d-11e7-81ab-22bb1e930703.png)

**Comment by rupinder1133** [comment]
exactly same issue with me as well

**Comment by hristo-kanchev** [comment]
@d07RiV I think both the undefined and NaN issues were fixed. Tried it locally and it works. Can you please check again? If it's fine, can you close the issue? Thanks!

**Comment by d07RiV** [comment]
Doesn't seem so. Using React Developer Tools 3.4.3, this code

```js
  state = {
    foo: parseInt("foo", 10),
    bar: undefined,
  }
```

shows up as just `foo: null`.

![image](https://user-images.githubusercontent.com/3448203/50005163-76fb9800-ffba-11e8-8d01-ce9b8174ae3f.png)

**Comment by hristo-kanchev** [comment]
@d07RiV For some reason I am not seeing this issue with the latest changes from `master`.
I'll check what's in it that might have fixed the issue.

Apologies!

**Comment by d07RiV** [comment]
Seems that messages are passing through JSON stringify/parse here (extensions::messaging):

```js
  // Called by native code when a message has been sent to the given port.
  function dispatchOnMessage(msg, portId) {
    var port = ports[portId];
    if (port) {
      if (msg)
        msg = $JSON.parse(msg);
      port.onMessage.dispatch(msg, port);
    }
  };
```

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
