### ISSUE TITLE
Chrome's Custom Formatters

### ISSUE THREAD

**Issue by roman01la** [facebook/react-devtools#989]
Hi! Is there any plans on supporting [Chrome's custom formatters](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview) to display custom data structures in readable format in React dev tools?

For example when debugging ClojureScript's immutable data structures we have a custom formatter that outputs data into the console in readable and inspectable format.

Here how it looks like
![screen shot 2018-02-19 at 3 02 32 pm](https://user-images.githubusercontent.com/1355501/36379156-39e8a882-1586-11e8-8973-7e6d3772cb4e.png)

And here's how data looks like in React Dev Tools inspector (basically underlying implementation of a data structure as seen in plain JS)
![screen shot 2018-02-19 at 2 59 04 pm](https://user-images.githubusercontent.com/1355501/36379177-4b280d90-1586-11e8-808d-ea7f2cebb274.png)

I think this can be done for React Dev Tools since once Custom Formatters are defined they are applied everywhere in Chrome's Dev Tools where it's possible to inspect data.

**Comment by roman01la** [comment]
Is react-devtools team at least interested in this change? I think ClojureScript community is eager to work on this if we have an approve from your side.

**Comment by Juholei** [comment]
This would be really great to get implemented.

**Comment by bvaughn** [comment]
My initial thoughts:
* This seems interesting and like it could help with inspecting certain data types.
* We probably won't want to invest time or effort into this for the current version of DevTools– but perhaps the rewrite I've recently started (since that will already be pulling props lazily from the backend).
* DevTools needs to support Firefox too, and it looks like Firefox doesn't support this. (Related issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1262914) So any integration would need to gracefully degrade.

I'd be interested in seeing a proof of concept 😄 but maybe not for a few weeks?

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
